import { Platform, StyleSheet } from 'react-native'
import { colors, spacing } from '@/lib/theme'

/** Web-only cursor for interactive rows and chips. */
export const webPointer = Platform.OS === 'web' ? ({ cursor: 'pointer' } as const) : {}

export const orgPanelStyles = StyleSheet.create({
  muted: {
    color: colors.textFaint,
    fontSize: 13,
    lineHeight: 18,
  },
  error: {
    color: colors.errorText,
    fontSize: 12,
    marginTop: 10,
    lineHeight: 16,
  },
  pageEyebrow: {
    color: colors.textDim,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  pageCopy: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  detailCard: {
    padding: spacing.md,
    borderRadius: 8,
    backgroundColor: colors.bgInset,
    borderWidth: 1,
    borderColor: colors.borderArea,
    gap: spacing.sm,
  },
  detailTitle: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  detailLine: {
    color: colors.stdout,
    fontSize: 12,
    fontFamily: 'monospace',
    lineHeight: 18,
  },
  detailLabel: {
    color: colors.textMuted,
  },
  expandedSection: {
    padding: spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderArea,
    backgroundColor: colors.bgSecondary,
    gap: spacing.sm,
  },
  commandCodeBlock: {
    padding: spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderMuted,
    backgroundColor: colors.bgInset,
    gap: spacing.xs,
  },
  statePanel: {
    padding: spacing.lg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderArea,
    backgroundColor: colors.bgArea,
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  statePanelTitle: {
    color: colors.textTitle,
    fontSize: 14,
    fontWeight: '600',
  },
  toolbarBtnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.bgActive,
  },
  toolbarBtnSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderChip,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.bgSecondary,
  },
  toolbarBtnTextPrimary: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  toolbarBtnTextSecondary: {
    color: colors.textChip,
    fontSize: 13,
    fontWeight: '600',
  },
  userChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderChip,
    backgroundColor: colors.bgSecondary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: 200,
  },
  userChipText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  calloutWarning: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.pending,
    backgroundColor: colors.bgSecondary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.pending,
  },
  calloutWarningText: {
    color: colors.pending,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  segmentGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderArea,
    backgroundColor: colors.bgInset,
    padding: 3,
    gap: 2,
    alignSelf: 'flex-start',
  },
  segmentChip: {
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minWidth: 44,
    alignItems: 'center',
  },
  segmentChipActive: {
    backgroundColor: colors.bgActive,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  segmentChipText: {
    color: colors.textDim,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'monospace',
  },
  segmentChipTextActive: {
    color: colors.accent,
    fontWeight: '700',
  },
})
